version: '{build}'
os: Visual Studio 2017
init:
  - git config --global core.autocrlf input
  - git config --global core.longpaths true
shallow_clone: true
build_script:
  build.cmd package
test: off
artifacts:
- path: artifacts\*.nupkg
  name: NuGetPackages
deploy: off
